### ISSUE TITLE
TypeError: app.consume is not a function

### ISSUE THREAD

**Issue by rudijs** [tjmehta/coworkers#12]
Hi,

I'm trying to get a consumer running, then publish to a queue and have the consumer process it.

I'm using the git repo for this tinkering code - not the npm module.

So trying to first fire up a consumer that consumes from the 'foo-queue'.

The consumer code is cut'n'paste from the README.

```
const app = require('./coworkers')()

/* shared middlewares */

// "trace" middleware
app.use(function * (next) {
  this.id = require('crypto').randomBytes(12)
  // save consumer start time
  const startTime = Date.now()
  // move on to next middleware
  yield next
  // all middlewares have finished
  const elapsed = Date.now() - startTime
  console.log(`coworkers-trace:${this.id}:${elapsed}`)
})

// "parse-content" middleware
app.use(function * (next) {
  this.message.content = JSON.parse(this.message.content)
  yield next
})

/* queue consumers w/ middlewares */

// "foo-queue" consumer middleware
app.consume('foo-queue', function * () {
  this.ack = true // checkout `Context` documentation for ack, nack, and more
})

app.connect()
```

Running this I get:

```
❯ node consumer.js
/projects/coworkers-demo/consumer.js:26
app.consume('foo-queue', function * () {
    ^

TypeError: app.consume is not a function
    at Object.<anonymous> (/projects/coworkers-demo/consumer.js:26:5)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

I'm using:

node -v                                                                                                                                         ⏎
v5.4.1
npm -v
3.3.12

Am I doing something wrong?

Thanks.

**Comment by tjmehta** [comment]
Change app.consume to app.queue

**Comment by tjmehta** [comment]
Sorry about that typo

**Comment by rudijs** [comment]
Ah OK cool.

That's OK now, but also needed and on error handler:

```
// "foo-queue" consumer middleware
app.queue('foo-queue', function * () {
  this.ack = true // checkout `Context` documentation for ack, nack, and more
})

app.on('error', function (err) {
  console.error(err.stack)
})

app.connect()
```

I have the consumer up and running OK now.

It's creating 8 connections and 16 channels, is that expected behavior?

**Comment by tjmehta** [comment]
Thanks!

Action Items:
 - [ ] Correct `app.consume` to `app.queue` in README
 - [ ] Add missing error handler in any full app examples in README

**Comment by tjmehta** [comment]
Oh sorry I didn't respond to your question.

Yes, 8 connections (1 per process) and 16 channels (2 per process) is correct.
Coworkers creates two channels per connection: one for consuming the worker's queue and one for publishing.
