### ISSUE TITLE
Question: Standalone Publishing

### ISSUE THREAD

**Issue by rudijs** [tjmehta/coworkers#13]
Hi,

I have a general type question on using coworkers.

I'm still a newb with this library, only spent and hour or so tinkering with it.

Is my assumption correct that coworkers is for consuming only?

I can see that while consuming, there is middleware for publishing, or send to queue - but that's part of the consuming process.

What about straight up publishing in it own process?

For example, from this gist, https://gist.github.com/rudijs/185fc162bdd667a91405, it will publish a message to RabbitMQ every 1 second.

Can I use coworkers to do the same thing? Or is coworkers more for just the consumer/processing side?

The gist example will create a new connection for each message (no channel).

Thanks

**Comment by tjmehta** [comment]
Coworkers was designed to be a rabbitmq consumer service framework. Currently, it only provides sugar to publishing w/in a consumer. 

But the coworkers app easily enables the use of it's underlying amqplib models. If you want to publish outside of consumer, just use app.publisherChannel directly (amqplib channel) after your coworkers app is connected.

**Comment by tjmehta** [comment]
There are also, plenty of other amqplib client libraries that provide more sugar with publishing: https://www.npmjs.com/search?q=rabbitmq

From my knowledge there are not many libraries to easily create rabbitmq consumer services.

Btw, feel free to keep the questions coming. I don't mind at all. Your feedback will be valuable as coworkers evolves.

Thanks

**Comment by rudijs** [comment]
> Coworkers was designed to be a rabbitmq consumer service framework

OK cool - thanks.

A consumer framework was the impression I had but just wanted to clarify I was on the correct path.

For sure I'll have more questions :-)

I'm a fan of RabbitMQ and intend to explore co-workers more.

I use Koa in my web apps as well.

I have also written and RPC pub/sub on top of amqplib: https://www.npmjs.com/package/amqp-rpc-factory

Thought is RPC only - can be used within Koa (publish) and also standalone.

I need a publish only (non RPC) - coworkers could fit in nicely.

Cheers.

**Comment by tjmehta** [comment]
Cool. I've thought about breaking out https://github.com/tjmehta/coworkers#context-methods, `request` and `reply` specifically, into a another library. `context.publish` and `context.sendToQueue` are just very thin wrappers above `amqplib`. Maybe I will break them out in the future. Closing this thread for now

**Comment by tjmehta** [comment]
Hey @rudijs,

I ended up needing this as well, so I broke out the rpc functionality from coworkers.

It's is not as robust as your module, it just exposes simple rpc helper utilities for amqplib.

https://github.com/tjmehta/amqplib-rpc

**Comment by rudijs** [comment]
Nice one Tejesh.

> I ended up needing this as well

I know what you mean, once you start you need them all - rpc, direct,
fanout.

Are you sending messages from an API server? For example KoaJS server?

I find RabbitMQ creeping into all aspects of my web development - client,
server, scripts, cronjobs, web sockets. End up needing all AMQP has to
offer.
