### ISSUE TITLE
Nesting Ack in function

### ISSUE THREAD

**Issue by tmcpro** [tjmehta/coworkers#22]
I'm loving the framework. I had a simple question about returning `this.nack = true` after my middleware consumes the message. 

My Flow is similar to this:
1. `app.queue('sendEmail', function*()`
2. Call a function to email the user 
3. Email Callback has `error` or `data`. 
4. If successful `this.ack = true;`
5. If error `this.reject=true`

Since I dont have access to `this` object within the `sendMail` function, what is the best way to return the ack on success, and reject on error?

**Comment by tjmehta** [comment]
Hey tmcpro, 

Thanks! I am glad you are enjoying using it.
I am on the go today, so here is a quick way of how I would do it.
Assuming your example is like this:
```js

function email (opts, cb) {
   // some async functionality...
}

app.queue('sendEmail', function * () {
  var opts = {....}
  yield email.bind(opts) // yield works with async functions that have callbacks
  this.ack = true
})

app.on('error', function (err, context) {
  console.error(err.stack)
  // reject, context.reject shortcut will not work in error handler...
  this.consumerChannel.reject(context.message, {})
    .then(function () {
      // reject success
    }).catch(function (err) {
      // reject fail
    })
})
```

If you don't want to generically handle all queue errors with nack you could also just wrap `email` w/ a `try..catch`:

```js
app.queue('sendEmail', function * () {
  var opts = {....}
  try {
    yield email.bind(opts) // yield works with async functions that have callbacks
    this.ack = true
  } catch (err) {
    console.error(err.stack) // log..
    this.reject = { requeue: false } // or requeue true..
    // this.reject = true requeues by default i think. check: http://www.squaremobius.net/amqp.node/channel_api.html#channel_reject
  }
})
``` 

Let me know if that helps, and let me know if you have any other questions or suggestions :)

**Comment by tjmehta** [comment]
Hey @tmcpro,

I am going to go ahead and close this out.
Please feel free to ask more questions and reopen it if you have any suggestions on improvement.

Thanks!
