### ISSUE TITLE
Support functions that return a promise.

### ISSUE THREAD

**Issue by tracker1** [tjmehta/coworkers#3]
It would be nice to support functions that return a promise...  To me this is a *much* cleaner abstraction.

## Using async functions...

```js
//consumer.js - async function
async function somethingUsingCoworker() {
  try {
    var message = { 'some': 'object' };
    var result = await app.work('queue-name', message); //pass all arguments after queueName to callee
    return result.
  } catch(err) {
    //err is the result of an error/fail from the coworker
    return null; //or rethrow
  }
}
/*****************************/
//worker.js - async function
app.worker('queue-name', async function(defer, message) { //all arguments after defer, from caller
  // reject the work, return error to caller/source
  throw new Error('...');

  //cannot process this work right now, re-queue
  return defer; // or throw defer, either should work

  //positive result that isn't defer, pass this result to caller/source
  return 'success'; 
}
```

## Using raw promises...

```js
//consumer.js - promise
function somethindUsingCoworker() {
  var message = {'some':'object'};
  return app.work('queue-name', message)
    .then(
      function(result) {
        //got result
        return result;
      },
      function(err) {
        //got error
        return null; //resolve, or throw err to rethrow, or return Promise.reject(err);
      }
    );
}
/*******************************/
//worker.js - promse
app.worker('queue-name', function(message, defer) {
  return new Promise(function(resolve, reject){
    //reject the work
    return reject(new Error(...));

    //defer/requeue the work
    return resolve(defer); // or return reject(defer); // either should work
    
    //positive result returned to calling process
    return resolve('success'); // anything that can be serialized as a response.
  });
})
```

**Comment by tjmehta** [comment]
I am not sure I fully understand what you're trying explain above.
Let me provide you some examples of using `Promises` w/ `coworkers` and see if it satisfies your use case. Co is used behind the scenes in coworkers and generators are used so that you can yield promises or node style async functions.

```js
const fs = require('fs')
const app = require('coworkers')()
const readFile = function (filepath) {
  return new Promise(function (resolve, reject) {
    fs.readFile(filepath, function (err, data) {
      if (err) { return reject(err) }
      resolve(data)
    })
  })
}

// shared middleware
// parse content as json
app.use(function * (next) {
  this.message.content = JSON.stringify(this.message.content.toString())
  yield next
})
// make sure filepath exists
app.use(function * (next) {
  assert(this.message.content.filepath, 'filepath is required')
  yield next
})

// read-file consumer, rpc queue
app.queue('read-file', 
  // since read-file is an rpc queue, 
  //   make sure it has replyTo and correlationId
  function * (next) {
    const props = this.message.properties
    assert(props.replyTo, 'replyTo is required')
    assert(props.correlationId, 'replyTo is required')
    yield next // continue
  },
  function * () {
    // yield the read file promise
    const fileData = yield readFile(this.message.filepath)
    // you can also yield node callback style functions.
    // the commented out line below is equivalent to yielding the promise
    // const fileData = yield fs.readFile.bind(fs, this.message.filepath)
    yield this.reply(fileData)
    // reply was successful
    this.ack = true
  })
// error handler
app.on('error', function (err, context) {
  console.error(err.stack)
  // if message has not been acked, nack it
  if (!context.messageAcked) {
    let channel = context.consumerChannel
    let message = context.message
    // use amqplib api, and make sure to handle errors in error handler
    context.consumerChannel.nack(message)
      .catch(function (err2) {
        console.error('nack failed', err.stack, err2.stack, message)
      }) 
  }
})
// ... connect etc...
```

**Comment by tracker1** [comment]
@tjmehta  I'm saying, that if the transport automatically JSON.stringify/parse messages, and simply relied on a defer option, the interface would be a *LOT* simpler...  The example I gave above, for async functions is *far* simpler than the complexity of your example.

Promises are a better abstraction for this type of work, and remote connection for a job than generators+co

**Comment by tjmehta** [comment]
Okay, I still have more questions:

What exactly does resolve(defer) do? Does that result in acking the message?

How do you provide downstream and upstream behavior for your promise example, eg a trace middleware that can be shared between queues?

**Comment by tracker1** [comment]
`resolve(defer)` or `reject(defer)` will drop out without acknowledging the message... hence it will be re-sent to another worker.

As for middleware/instrumentation, not sure... I hadn't considered instrumentation beyond `EventEmitter`-style events. that could be built in...  emitting using [process.hrtime()](https://nodejs.org/api/all.html#all_process_hrtime) and/or `Date.now()`

**Comment by tjmehta** [comment]
Also, I am not sure you saw the second question about multiple async behaviors (I edited the question shortly after posting it).

If multiple async behaviors have to be resolve through by chaining `thens` I would still argue that the generator solution is simpler. However, maybe you can enlighten me. 

Side note: I think [koa](https://github.com/koajs/koa) does support `async` functions. I did not include that behavior in coworkers yet but I assume that you can can somehow use `defers` in place of `yields` when using `async` functions. I just don't have enough experience w/ async and defer yet, so I didn't want to include it without actually using it first.

**Comment by tracker1** [comment]
`defer` would be something you pass in...

```
const defer = function(){ return defer; }; //in case someone does something like return defer();
...
//assume respond, sends the response to the client
// call worker with arguments... workerFunction is what was passed in to queue.worker(workerFunction)
workerFunction(defer, ...args)
  .then(function(result){
    //defer, don't ack, don't send response
    if (result === defer) return; //no ack, no response, will requeue
    
    //respond to the client that the promise is resolved
    respond({result:'resolve',resolve:result});
  })
  .catch(function(err){
    if (result === defer) return; //no ack, no response, will requeue

    //respond and ack
    err = cloneWithErrorProps(err); //make sure message and stack are cloned for stringify
    respond({result:'error',error:err});
  });
```

NOTE: defer could just be exported as a constant... then not pass it into the function at all... special handling would be the same...

```
    return coworkers.DEFER;
```

multiple async behaviors...

```
// https://www.npmjs.com/package/thenify
app.worker('foo', async function(defer, ...args) {
  const path = await new Promise(...)
  const size = await new Promise(...)

  const data = await thenify(fs.readFile)(path);

  // returning a value that isn't defer...
  //   returns that value to the caller, and sets ack to true.
  return ...;

  return defer; // no ack
  throw defer; // no ack

  throw ...; // ack and return the result as the reject action on the client.
});
```

There is no need to worry about yeilding control...  As for `async` functions, the function above is the effectively the same as...

```
const readFile = thenify(fs.readFile);
app.worker('foo', function(defer, ...args) {
  let path, size;
  return new Promise(...)
    .then(function(d){
      path = d;
      return new Promise(...);
    })
    .then(function(s){
      size = s;
      return readFile(path);
    })
    .then(function(data){
      return ...; //successful result - do ack

      return defer; //no response - no ack
      throw defer; //no response - no ack

      throw new Error(); //something else thrown, reject == ack with rejected result
    });
});
```

While promise chaining is a pain, you can see from the async example that the code is much simpler, and there's no need to utilize co/koa style thunks for workers as they should either resolve or reject...

**Comment by tjmehta** [comment]
Apologies, I confused 'defer' with 'await'. Catching up on your example now

**Comment by tjmehta** [comment]
So there is actually another framework called ponos that is a promised based rabbitmq framework. Sounds like it is very similar to what you are proposing here: https://github.com/runnable/ponos
Thank you for taking the explain your api examples to me, and let me know if ponos is closer to the api you are looking for.

As for coworkers:
One of coworker's goals is to enable users to have async behavior while avoiding `then` chaining and `callbacks`. I also wanted enable middlewares to flow "downstream" and "upstream" for powerful composability. Finally, mirroring koa's api allows the use of some of koa's existing ecosystem (either directly or w/ some tweaks). 

It is my opinion, that using generators w/ yields is cleaner and more flexible.
Keep in mind, you can actually still use promise chaining with koa, if that is your preferred coding style (but it requires at least a single yield at the beginning of a promise chain).
```js
app.use(function * (next) {
  yield return new Promise(...)
    .then(function(d){
      path = d;
      return new Promise(...);
    })
    .then(function(s){
      size = s;
      return readFile(path);
    })
    .then(function(data){
      return this.ack = true

      return next; // proceed to the next middleware if one exists
      return //no response, error - no ack

      throw new Error(); // throw error to error handler, handle it there w/ reject, nack, or w.e
    });
})
```

**Comment by tjmehta** [comment]
Going to go ahead and close this out due to the reasons listed above. Thanks for your input and let me know if https://github.com/runnable/ponos works out for you
