### ISSUE TITLE
app.publisherChannel unexpectedly closed

### ISSUE THREAD

**Issue by melalj** [tjmehta/coworkers#36]
When I close the app: app.close(),
I get an `uncaughtException: "app.publisherChannel" unexpectedly closed`

It looks like publisherChannel is not closed in this part of the code:  https://github.com/tjmehta/coworkers/blob/aecc91bb2eb87bd929ebaaeec7311ca0065dec2b/lib/application.js#L350

**Comment by tjmehta** [comment]
checking this out

**Comment by tjmehta** [comment]
fixed coworkers@v0.6.1

**Comment by tjmehta** [comment]
lmk if you still have problems

**Comment by melalj** [comment]
It's working 👍 
Thanks!
