### ISSUE TITLE
How do you set a prefetch count for consumers?

### ISSUE THREAD

**Issue by spencerapplegate** [tjmehta/coworkers#38]
I am using a round robin method of processing where I want each consumer to have a specific prefetch to control memory usage per box. At the moment, if I have thousands of messages on a queue, my consumer will fetch all of them down to process simultaneously. Obviously, this is causing severe memory issues on my consumers. I would like to set a prefetch count to control the flow at a finer level. I have done this in the past with the amqplib library, but cannot exactly see how to do it w/ coworkers. Is there currently a way to achieve this?

**Comment by tjmehta** [comment]
Hey Spencer,

`app.queue` accepts options for `amqplib`'s `channel.assertQueue` and `channel.consume`. So just pass the appropriate options to `app.queue`

Options usage:
```js
app.queue(queueName, [queueOpts], [consumeOpts], ...middlewares)
// options are used w/ amqplib calls during `app.connect`:::
channel.assertQueue(queueName, queueOpts) // queueOpts!
channel.consume(queueName, _handler, consumeOpts) // consumeOpts!
```

Check out the code:
https://github.com/tjmehta/coworkers#appqueuequeuename-queueopts-consumeopts-middlewares

Let me know if you have anymore questions

**Comment by spencerapplegate** [comment]
@tjmehta In [Amqplib's channel.consume documentation](http://www.squaremobius.net/amqp.node/channel_api.html#channel_consume) I only see the ability to set options `consumerTag`, `noLocal`, `noAck`, `exclusive`, and `priority`. I do not see an option there to set the prefetch count.

Could you please include a more specific example on how to do so through coworkers?

**Comment by tjmehta** [comment]
Sorry, assumed that it was an option. I understand the problem now. You can call channel methods directly on the `consumerChannel`.

I haven't used prefetch, so I am not sure when if it is okay to call it _after_ coworkers is consuming queues.
```js
// setup queues...
app.connect(...).then(function () {
  app.consumerChannel.prefetch(...)
})
```

Would that work. Is it required to set prefetch before consuming jobs from queues?

**Comment by spencerapplegate** [comment]
@tjmehta Unfortunately you must call it before consumers start consuming messages or the flood gate of messages has already begun. Any way we could call it during the connect cycle within coworkers?

**Comment by tjmehta** [comment]
Unfortunately, currently no, but we can definitely add it!

The assertion and binding happens back to back here:
https://github.com/tjmehta/coworkers/blob/master/lib/rabbit-utils/assert-and-consume-app-queue.js

I guess we could add a prefetch option somewhere.. either `connect` or `queue`. Let me know if you have any suggestions and we can get the functionality in ASAP.

**Comment by spencerapplegate** [comment]
@tjmehta I'll submit a PR in the next week or so! I see your your note about using coworkers-test for testing consumers, but do you have a good way of testing during development?

**Comment by tjmehta** [comment]
Cool, I may be able to hack it up for you sooner too. 

I'm not sure what you mean by during development. But I think coworkers-test is a great way to test during development. It allows you test your consumers as a unit without having to connect to a rabbitmq

**Comment by tjmehta** [comment]
Added `app.prefetch` method in coworkers@v0.7.0. Let me know if you have any other problems!

Thanks!
