### ISSUE TITLE
Would you please give some example with Mongoose and MongoDB?

### ISSUE THREAD

**Issue by SoaringTiger** [tjmehta/coworkers#47]
@tjmehta 
I want to use coworkers to work with Mongoose and MongoDB, would you please give some examples?

**Comment by tjmehta** [comment]
Coworkers does not have any helpers for organizing database models. It is just a framework creating a rabbitmq consumer application. If you are wanting to create an application that "replies" database "rows" checkout the RPC example: https://github.com/tjmehta/coworkers#rpc--request-reply-checkreplyqueue-example

**Comment by SoaringTiger** [comment]
@tjmehta thanks
