### ISSUE TITLE
Opening exclusive queue per request and leaving them open

### ISSUE THREAD

**Issue by combsco** [tjmehta/coworkers#48]
I've had this problem with the [amqplib-rpc](https://github.com/tjmehta/amqplib-rpc) library. I was trying to use `amqplib-rpc` on my API Gateway and it would just keep creating new exclusive channels. I had to switch to [node-bunnymq](https://github.com/dial-once/node-bunnymq) because it creates one exclusive queue for responses.

So if I run this code 4 times... I get 4 exclusive queues that don't delete themselves until Coworkers process is killed. This is following the [RPC example from the readme](https://github.com/tjmehta/coworkers#rpc--request-reply-checkreplyqueue-example)...

![Imgur](http://i.imgur.com/EmLee6Q.png)

### Client
```js
app.use(function * (next) {
  if (this.queueName === 'user.create') {
    const replyMsg = yield this.request('tenant.read', {tenant_id: this.message.content.tenant_id})
    // do something with replyMsg
  }
  yield next
})
```

### Server
```js
app.queue('tenant.read', function * () {
  // return the good stuff...
  this.reply(new Buffer(JSON.stringify(result))
  this.ack = true
})
```

**Comment by tjmehta** [comment]
Wow. Definitely a bug. I haven't used coworkers rpc in my apps. So I will definitely fix this ASAP. If you have a moment, please help by adding a broken test. Although, this seems like a bug with amqplib-rpc

Typed using my thumbs..

**Comment by tjmehta** [comment]
Have a fix coming very soon: https://github.com/tjmehta/amqplib-rpc/pull/10

**Comment by tjmehta** [comment]
fixed coworkers@v0.7.2

**Comment by tjmehta** [comment]
Turns out exclusive queues do not auto-close when their channel is closed.

**Comment by combsco** [comment]
Awesome thanks for the update!

**Comment by tjmehta** [comment]
Np, lmk if you hit any other problems or have any questions
