### ISSUE TITLE
Require in index.js

### ISSUE THREAD

**Issue by mdrobny** [tjmehta/coworkers#5]
I have an error when requiring
`const coworkers = require('coworkers');`
Error occurs at line:
https://github.com/tjmehta/coworkers/blob/master/index.js#L1

When changed to `module.exports = require('./lib/application')` it works for me. Am I doing something wrong?

**Comment by tjmehta** [comment]
Well, that's a silly mistake. I have been running it linked locally, somehow the error didn't show. I will fix this right away. Thanks

**Comment by tjmehta** [comment]
coworkers@v0.1.1

**Comment by mdrobny** [comment]
:+1:
