### ISSUE TITLE
Clustering / Process management ( DISABLE )

### ISSUE THREAD

**Issue by protzi** [tjmehta/coworkers#51]
Hello, i try to use coworkers and rabbitmq-schema;
if for some reason i want to disable workers, and left only ONE, but i have two or more queue, how to properly use 1 worker ( = 1 process ) ?

```
process.env.COWORKERS_CLUSTER = false;
process.env.COWORKERS_QUEUE = 'queue1'; <= should i define here 1 queue or more ?
//process.env.COWORKERS_QUEUE_WORKER_NUM = 1;
```

**Comment by tjmehta** [comment]
Hey Protzi,

Sorry for making you wait days for a reply.
I believe what you have so far is correct

To manage your queue processes manually specify env for each of your process independently.

For your `queue1` process specify:
```js
process.env.COWORKERS_CLUSTER = false;
process.env.COWORKERS_QUEUE = 'queue1';
```
For your `queue2` process specify:
```js
process.env.COWORKERS_CLUSTER = false;
process.env.COWORKERS_QUEUE = 'queue2';
```

And so on.

Does that make sense?

**Comment by protzi** [comment]
ok it seems make sense, but if i have multiple queues for 1 process ? Or its a bad idea ?:)

```
process.env.COWORKERS_CLUSTER = ? 
process.env.COWORKERS_QUEUE = ?
COWORKERS_QUEUE_WORKER_NUM= ?
```

```
app.queue('firstQueue'...

app.queue('secondQueue'...
```

**Comment by tjmehta** [comment]
There is no way to have multiple queues in 1 process using coworkers. When you use clustering, coworkers creates a child process per queue. When disabling clustering you are specifying a queue per process manually using environment variables.
