### ISSUE TITLE
What to do if a want to ack asynchronously?

### ISSUE THREAD

**Issue by dilame** [tjmehta/coworkers#57]
I have long async task, that i want to ack/nack only after it finish. How can i implement this with coworkers? As i see, i can ony do it with context properties, but in case with RabbitMQ and JS this is unusable almost always.
Or did I understand something wrong?

**Comment by tjmehta** [comment]
I am not sure what you mean exactly. Here’s a simple example acking after an async task:
```
app.use(function * () {
  yield Promise.resolve()
  this.ack = true
})
```

**Comment by dilame** [comment]
@tjmehta you understand me right. Thank you.
But what if in the end i want to nack, depends on result of promise?

**Comment by tjmehta** [comment]
```
app.use(function * () {
  const result = yield Promise.resolve(‘foo’)
  If (result === ‘foo’) {
    this.ack = true
  } else {
    This.nack = true
  }
})
```

-or-

```
app.use(function * () {
  let result
  try {
    result = yield Promise.resolve(‘foo’)
    this.ack = true
  } catch (err) {
    this.nack = false
  }
})
```

**Comment by tjmehta** [comment]
I am going to close this issue, but please feel free to continue asking questions here and I will answer any you have :)

**Comment by dilame** [comment]
Thank you! 
Can i use https://github.com/nswbmw/koa-mongo for mongodb connection? 
If no, what is the best practice for this?

**Comment by tjmehta** [comment]
coworkers is not 100% compatible with koa plugins. But you could copy patterns you see in koa plugins. I typically just open up a single db connection on application start.
