### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by p1nox** [tjmehta/coworkers#60]
First thing, the concept of this package is awesome 💯, I hope you are going to keep maintaining it 👍. Second, not sure if I can post a question here about framework docs.

In case of application loose connection to rabbit, is it going to try to reconnect? I don't find docs about that. I read that `If any of the workers fail to connect to Rabbitmq they will cause master's connect to error.` https://github.com/tjmehta/coworkers#appconnect , but I guess this is when trying to connect the first time, or is it also when loosing connection after successfully connecting the first time?

**Comment by tjmehta** [comment]
Hey sorry for the late reply. If any worker's connection disconnects they will throw a connection error, crash itself, and the master will create a new worker.

**Comment by tjmehta** [comment]
Feel free to reopen if you have more questions!
