### ISSUE TITLE
What is the maintenance status of this project? Is this approach better than Seneca / Cote etc?

### ISSUE THREAD

**Issue by chaudhryjunaid** [tjmehta/coworkers#61]
I am interested in developing node.js microservices using rabbitmq as the messaging framework. I stumbled upon this project which seemed like the ideal approach to such a solution. However, I want to know if the project is being maintained as the last commit was over an year ago.

Also, does this approach prove superior to other approaches such as Seneca or Cote when developing microservices? I appreciate the bare metal nature of the rabbitmq approach which to me provides a clearer model of the communication going on between microservices. Are there other considerations that need to be taken into account?

**Comment by chaudhryjunaid** [comment]
@tjmehta: would appreciate a reply!

**Comment by tjmehta** [comment]
I am not actively updating the project at the moment (my services still using it are live but not under active development), but I am open to pull requests.

**Comment by tjmehta** [comment]
Going to close this but feel free to ask question via twitter https://twitter.com/tjmehta
