### ISSUE TITLE
How should I work with exchanges?

### ISSUE THREAD

**Issue by littledesu** [tjmehta/coworkers#9]
My application example:
```javascript
'use strict';

const coworkers = require('coworkers');
const RabbitSchema = require('rabbitmq-schema');

const schema = new RabbitSchema({
  exchange: 'my-existing-exchange',
  type: 'direct',
  bindings: [{
    routingPattern: 'foo.bar.key',
    destination: {
      queue: 'queue0',
      messageSchema: {}
    }
  }]
});

const app = coworkers({schema: schema});
app.queue('queue0', function * () {
  this.ack = true;
});

app.on('error', function (err) {
  console.error(err.stack)
});

app.connect('amqp://my-rabbitmq-url');
```
After launching the application, the 'queue0' is being created, but it does not bind to the exchange:
![screen shot 2016-01-27 at 12 57 48](https://cloud.githubusercontent.com/assets/825300/12609891/a5c48a00-c4f5-11e5-8864-0a6ae2f7a0cd.png)
What am I doing wrong?

**Comment by tjmehta** [comment]
Hi @littledesu. Currently coworkers only asserts the queue's specified via `app.queue(...)`. I have not found best practices for where to assert queues, exchange, binding assertions, so I have only assumed to assert what the coworkers application actually uses.

`rabbitmq-schema` provides nice methods for traversing your rabbitmq schema.

For example, if you just want to assert everything in the example you provided, checkout the example here:
https://github.com/tjmehta/rabbitmq-schema/blob/master/README.md#list-exchanges-w-bindings-and-queues

After I fix: https://github.com/tjmehta/coworkers/issues/8 and if you are using clustering
You will be able to avoid asserting queues by waiting for the master `app.connect(...)` to resolve. I will explain this in more detail, once it is complete.

Let me know if you have any other questions or suggestions.

Thanks for you question/input so far :)

**Comment by tjmehta** [comment]
Going to give you a quick response for now as I am swamped w/ work. I did actually change the implementation of the `connect` in the "master process"; it will now yield (cb or resolve) AFTER all the workers have successfully started, connected to rabbitmq, and assert and bind their queues.

As a result you can setup something like this:
```js
/* <app middleware setup> */

co(function * () {
  if (cluster.isMaster) {
    /* <assert your exchanges - checkout rabbitmq schema docs> */
    yield app.connect()
    // all queues used w/ coworkers are guaranteed to be asserted here
    /* <assert your bindings - checkout rabbitmq schema docs> */
  } else {
    yield app.connect()
  }
}).catch(function (err) {
  process.nextTick(function () {
    throw err
  })
})
```

That is my solution for now, so let me know if you have any questions or other suggestions.

I am closing this ticket, but feel free to respond here! Thanks!
